# 设置 Gradle 命令的默认内存。可由用户或命令行属性覆盖
org.gradle.jvmargs=-Xmx1G
# 指向本地 JDK 21（不依赖系统环境变量 JAVA_HOME）
org.gradle.java.home=C\:\\BinApps\\Java\\jdk21
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# 更多信息请参阅: https://github.com/neoforged/ModDevGradle?tab=readme-ov-file#better-minecraft-parameter-names--javadoc-parchment
# 最新版本可在以下位置找到: https://parchmentmc.org/docs/getting-started
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
# 环境属性
# 最新版本请见: https://projects.neoforged.net/neoforged/neoforge
# Minecraft 版本必须与 Neo 版本一致才能获得有效制品
minecraft_version=1.21.1
# Minecraft 版本范围可以使用任何 Minecraft 正式版作为边界
# 快照版、预发布版和候选发布版因不遵循标准版本命名规范，无法保证正确排序
minecraft_version_range=[1.21.1]
# Neo 版本必须与 Minecraft 版本一致才能获得有效制品
neo_version=21.1.235
# 加载器版本范围只能使用 FML 的主版本号作为边界
loader_version_range=[1,)

## 模组属性

# 模组的唯一标识符。必须使用英文小写字母。必须匹配正则表达式 [a-z][a-z0-9_]{1,63}
# 必须与主模组类中 @Mod 注解的 String 常量一致
mod_id=cnpcef
# 模组的人类可读名称
mod_name=CNPC-EpicFight-Addon-CE
# 游戏中显示的模组名称（包含版本号）
mod_display_name=CNPC-EpicFight-Addon-CE-1.21.1
# 模组的许可证。可在 https://choosealicense.com/ 查看你的选项。默认为 All Rights Reserved
mod_license=All Rights Reserved
# 模组版本。参见 https://semver.org/
mod_version=1.21.1-NeoForge
# 模组的组 ID。仅当发布到 Maven 仓库时才有意义
# 应与模组源码的基包名一致
# 参见 https://maven.apache.org/guides/mini/guide-naming-conventions.html
mod_group_id=top.bincnpcef
# 模组作者
mod_author=Bin
